# Generated by Django 5.2.5 on 2025-12-27 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='peliculas/')),
                ('calificacion', models.FloatField(default=0.0, help_text='Calificación de 0 a 10 (ej: 8.5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria')),
                ('recomendado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.participante')),
            ],
        ),
    ]
