# Generated by Django 5.2.5 on 2025-12-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.IntegerField(),
        ),
    ]
