# Generated by Django 5.2.5 on 2025-12-27 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_pelicula_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
