# Generated by Django 5.2.5 on 2025-12-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_pelicula_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.PositiveIntegerField(default=0, help_text='del 1 al 10'),
        ),
    ]
