# Generated by Django 5.2.5 on 2025-12-27 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_pelicula_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
