# Generated by Django 5.2.5 on 2025-12-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_pelicula_calificacion_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.FloatField(default=0),
        ),
    ]
